#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=InstallEnvironment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=6
#SBATCH --time=02:00:00
#SBATCH --output=job_outs/install_env_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

root=/scratch-local/$USER/ATinCS
mkdir -p $root

env_dir=$HOME/ATinCS
source activate practical1
# python -m pip install scikit-learn
conda env create -f $env_dir/environment.yaml

# Check the dependencies
conda list
