#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=toxi-finetune-2
#SBATCH --ntasks=1
#SBATCH --time=04:00:00
#SBATCH --mem=64000M
#SBATCH --output=job_outs/toxi-finetune-2_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

# Activate your environment
source activate acts_xling_gpu_env
pip install seqeval
pip install evaluate
pip install --upgrade datasets pyarrow transformers
pip install accelerate -U
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# Run code
bash job-files/toxi-finetune.sh
