#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gres=gpu:1
#SBATCH --cpus-per-task=9
#SBATCH --gpus=1
#SBATCH --job-name=xnli-finetune
#SBATCH --ntasks=1
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=job_outs/xnli-finetune_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

conda env create -f gpu_env.yml

# Activate your environment
source activate acts_xling_gpu_env

# Run code
bash job-files/xnli-finetune.sh
